routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if (User::all()->count() == 0) return redirect('/register'); else return redirect('/admin'); 
    return view('welcome');
});

Auth::routes(['register' => false]);

//Admin
Route::group(['middleware' => ['auth']], function() {
    Route::resource('users','UserController');
    Route::resource('branches','BranchController');
});

Route::get('/register', function () {
	if (User::all()->count() == 0) return App::call('App\Http\Controllers\Auth\RegisterController@showRegistrationForm');
})->name('register');

Route::post('/register', 'Auth\RegisterController@register');

Route::get('/admin', 'HomeController@index')->name('admin');
Route::post('/guest_registration', 'GuestController@saveGuestDetails')->name('save_guest_registration');
Route::get('/guest_registration', 'GuestController@showGuestForm')->name('guest_registration');
Route::get('/guestlog', 'GuestController@showGuestLog')->name('guest_registration_log');
Route::get('/guestlogfile', 'GuestController@outputGuestLog')->name('export_guest_registration_log');

Route::get('/change_password', 'UserController@ShowChangePassword')->name('show_change_password');
Route::post('/change_password', 'UserController@SavePassword')->name('update_password');

app/Branch.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Branch extends Model
{

	use Notifiable;

	protected $table = 'tbl_branch';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'branch_name',
        'hashedbranchname',
    ];

}

app/Http/Controllers/BranchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use App\Http\Controllers\Controller;
use App\Branch;
use Hash;

class BranchController extends Controller
{
	function __construct()
    {

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = Branch::orderBy('id','DESC')->paginate(5);
        return view('branch.index',compact('data'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('branch.create');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'branch_name' => 'required'
        ]);

        $input = $request->all();
        $input['hashedbranchname'] = Str::uuid();
        $branch = Branch::create($input);

        return redirect()->route('branches.index')
                        ->with('success','Branch created successfully');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $branch = Branch::find($id);
        return view('branch.show',compact('branch'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $branch = Branch::find($id);
        
        return view('branch.edit',compact('branch'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'branch_name' => 'required'
        ]);

        $branch = Branch::find($id);
        $input = $request->all();
        $branch->update($input);

        return redirect()->route('branches.index')
                        ->with('success','Branch updated successfully');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Branch::find($id)->delete();
        return redirect()->route('branches.index')
                        ->with('success','Branch deleted successfully');
    }
}

resources/views/branch/create.blade.php
@extends('layouts.app')


@section('content')

<div class="container-fluid">
    
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Branch Maintenance | New Branch</h1>



    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a class="btn btn-primary" href="{{ route('branches.index') }}"> Back</a>
        </div>
        <div class="card-body">

        @if (count($errors) > 0)
          <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
               @foreach ($errors->all() as $error)
                 <li>{{ $error }}</li>
               @endforeach
            </ul>
          </div>
        @endif



    {!! Form::open(array('route' => 'branches.store','method'=>'POST')) !!}
            <div class="row">
                <div class="col-xs-3 col-sm-6 col-md-4">
                    <div class="form-group">
                        <strong>Branch Name:</strong>
                        {!! Form::text('branch_name', null, array('placeholder' => 'Branch Name','class' => 'form-control')) !!}
                    </div>
                </div>
            </div> 
            <div>
                </div>
                <div class="col-xs-3 col-sm-3 col-md-4 text-right">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
    {!! Form::close() !!}

    </div>
    
</div>

@endsection

resources/views/branch/edit.blade.php
@extends('layouts.app')


@section('content')

<div class="container-fluid">
    
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Branch Maintenance | Edit Branch</h1>



    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a class="btn btn-primary" href="{{ route('branches.index') }}"> Back</a>
        </div>
        <div class="card-body">

        @if (count($errors) > 0)
          <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
               @foreach ($errors->all() as $error)
                 <li>{{ $error }}</li>
               @endforeach
            </ul>
          </div>
        @endif


            {!! Form::model($branch, ['method' => 'PATCH','route' => ['branches.update', $branch->id]]) !!}
            <div class="row">
                <div class="col-xs-3 col-sm-6 col-md-4">
                    <div class="form-group">
                        <strong>Branch Name:</strong>
                        {!! Form::text('branch_name', null, array('placeholder' => 'Branch Name','class' => 'form-control')) !!}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3 col-sm-3 col-md-4 text-right">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
</div>

@endsection

resources/views/branch/index.blade.php
@extends('layouts.app')


@section('content')

        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Branch Maintenance</h1>
          
          @if ($message = Session::get('success'))
          <div class="alert alert-success">
            <p>{{ $message }}</p>
          </div>
          @endif


          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <a class="btn btn-success" href="{{ route('branches.create') }}">New Branch</a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th width="80px">No</th>
                      <th>Branch Name</th>
                      <th width="280px">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($data as $key => $branch)
                    <tr>
                      <td>{{ ++$i }}</td>
                      <td>{{ $branch->branch_name }}</td>
                      <td>
                        <a class="btn btn-info" href="{{ route('branches.show',$branch->id) }}">Show</a>
                         <a class="btn btn-primary" href="{{ route('branches.edit',$branch->id) }}">Edit</a>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
                {!! $data->render() !!}
              </div>
            </div>
          </div>

        </div>

@endsection

resources/views/branch/show.blade.php
@extends('layouts.app')


@section('content')

<div class="container-fluid">
    
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Branch Maintenance | Branch Details</h1>



    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a class="btn btn-primary" href="{{ route('branches.index') }}"> Back</a>
        </div>
        
        <div class="card-body">

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Branch Name:</strong>
                        {{ $branch->branch_name }}
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>URL for Customer Registration:</strong><br>
                        {!! url("/guest_registration?v=" . $branch->hashedbranchname) !!}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>QR Code for Customer Registration:</strong><br>
                        {!! QrCode::size(300)->generate(url("/guest_registration?v=" . $branch->hashedbranchname)); !!}
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

@endsection